'3':
  '1': silentmessages %name%
  '2': give %name% potion 2 effect:slowness power:1 duration:5
'5':
  '1': silentmessages %name%
'7':
  '1': silentmessages %name%
'10':
  '1':  silentmessages %name%